[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "n8n"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[healthcheck]
path = "/healthz"
timeout = 10
interval = 30

[settings]
region = "us-west1"